import React from "react";

function Terms() {
  return (
    <div style={{ padding: "20px" }}>
      <h1>Terms of Service</h1>
      <p>
        This service summarizes restaurant reviews for informational purposes only.
        Users are responsible for how they use the summaries generated by this tool.
      </p>
    </div>
  );
}

export default Terms;
